//! Attention: where to put it, for a minute.
//!
//! The terse deck, and the one nearest the Oblique Strategies cards that are
//! only a noun - `Water`, `Ghost echoes`, `Accretion`. Every card is written
//! for this crate. The register comes from Thoreau watching a pond through a
//! year, from haiku, from Zhuangzi and the Tao Te Ching on the usefulness of
//! what is not there, and from Sei Shonagon's habit of keeping lists of things
//! worth noticing. No card quotes any of them.
//!
//! The deck points outward. No card addresses the reader as `you`, and none
//! asks a question; both rules are enforced when the deck is generated, along
//! with a sixty-character ceiling that keeps the cards short enough to hold in
//! the head while looking at something else.

use crate::{Deck, Provenance};

/// The attention deck.
pub const DECK: Deck = Deck {
    id: "attention",
    name: "Attention",
    blurb: "Where to put it, for a minute.",
    provenance: Provenance::Original,
    cards: CARDS,
};

const CARDS: &[&str] = &[
    "A weed doing well.",
    "Attend to the pause, not the note.",
    "Count the sources of light.",
    "Count what there is too much of.",
    "Do not name it. Keep looking.",
    "Elegant things\n\t-in this room\n\t-outside it",
    "Follow one echo to where it stops.",
    "Hands, not faces.",
    "Light, before it is named.",
    "Listen for what stopped.",
    "Listen until it is dull. Keep listening.",
    "Look again in an hour.",
    "Look down.",
    "Look up.",
    "Marks left by use.",
    "Moss. Where, and why there.",
    "Name three sounds. Then a fourth.",
    "Nothing is happening. Watch that.",
    "Notice\n\t-the near\n\t-the far\n\t-the middle",
    "One insect, followed to the end.",
    "One square inch, for one minute.",
    "Return tomorrow at the same time.",
    "Same window, a different hour.",
    "Silence has a texture. Find it.",
    "Something very small, very close.",
    "Stay a minute past comfortable.",
    "Steam and condensation, the same thing twice.",
    "Stop describing. Keep watching.",
    "Taste something without naming it.",
    "The animal that was here first.",
    "The brightest thing in the room.",
    "The ceiling.",
    "The color of the shadow, not the object.",
    "The corner nothing happens in.",
    "The day turning over.",
    "The distance people leave between them.",
    "The farthest visible thing.",
    "The first cold morning.",
    "The gap where something used to be.",
    "The grain under the paint.",
    "The hour the birds stop.",
    "The last lit thing at dusk.",
    "The last thing to stop moving.",
    "The line the water left.",
    "The middle distance.",
    "The oldest object in the room.",
    "The path worn beside the path.",
    "The pitch of the refrigerator.",
    "The room is the space, not the walls.",
    "The room's own noise.",
    "The shape of the missing piece.",
    "The slowest moving thing in view.",
    "The smell of the room on returning to it.",
    "The sound arriving from farthest away.",
    "The sound of someone else's work.",
    "The sound under the sound.",
    "The temperature of the doorknob.",
    "The thing passed daily and never once seen.",
    "The useful part of a cup is the empty part.",
    "The weight of an ordinary object.",
    "The whole, then a part, then the whole.",
    "Things that are pleasing\n\t-and small\n\t-and worn",
    "Things that arrive quietly\n\t-name three",
    "Touch something without looking at it.",
    "Turn around.",
    "Watch one surface until the light leaves it.",
    "Watch something fall.",
    "Watch water take the shape of what holds it.",
    "Water finds the low place.",
    "Wear is a record. Read it.",
    "What arrived without being planted.",
    "What casts no shadow.",
    "What grows in the crack.",
    "What hands do while waiting.",
    "What has been repaired.",
    "What has been worn smooth.",
    "What is behind.",
    "What is colder than the room.",
    "What is different from a week ago.",
    "What is missing that no one mentions.",
    "What is still, and what only seems still.",
    "What is under the furniture.",
    "What is warm that should not be.",
    "What moves only when unwatched.",
    "What sits exactly at eye level.",
    "What the air smells of at this hour.",
    "What the building does at night.",
    "What the gap is for.",
    "What the rain does to the smell of a street.",
    "What the season is doing to the light.",
    "What was here before this was here.",
    "Where the light lands now.",
    "Who is quiet in the room.",
];
