//! Constraints: rules to write against.
//!
//! A procedure is not copyrightable; the words someone used to describe one
//! are. Every card here restates a method in its own words, and none quotes a
//! source. The methods come from the Oulipo (the lipogram, the univocalism,
//! the snowball, definitional literature, and substituting a word for the nth
//! that follows it in a dictionary), from Dada and Surrealist practice (words
//! drawn from a bag, the cut-up and the fold-in, the folded sheet passed hand
//! to hand, writing without steering), and from the ordinary workshop stock of
//! subtraction, retelling and changed vantage.
//!
//! Take one and obey it further than seems reasonable.

use crate::{Deck, Provenance};

/// The constraints deck.
pub const DECK: Deck = Deck {
    id: "constraints",
    name: "Constraints",
    blurb: "Rules to write against.",
    provenance: Provenance::Technique("Oulipo, Dada and Surrealist procedures, restated"),
    cards: CARDS,
};

const CARDS: &[&str] = &[
    "Add a character who says nothing.",
    "Add to each paragraph one sentence that contradicts it.",
    "Allow yourself only words of one syllable for a page.",
    "Ban the three commonest letters in what you just wrote. Write it again.",
    "Begin every word of a paragraph with the same letter.",
    "Between every two sentences, write a third.",
    "Black out most of a page you did not write. Keep what is left.",
    "Borrow the structure of the last thing you read and discard its subject.",
    "Choose a word that may not appear. Write around its absence.",
    "Choose one to forbid\n\t-a letter\n\t-a word\n\t-a tense",
    "Compress a year into a paragraph, then a minute into a page.",
    "Cut a page of newsprint into single words. Shake them in a bag. Copy them out as they come.",
    "Cut the first paragraph and begin at the second.",
    "Cut the last paragraph and end at the one before.",
    "Cut the sentence you are proudest of.",
    "Cut the text\n\t-in half\n\t-in half again",
    "Cut two pages down the middle. Join the left of one to the right of the other.",
    "Decide the shape before you decide the subject.",
    "Delete every adjective. Read it aloud. Put back only what you miss.",
    "Delete every dialogue tag. Let the speech carry who is speaking.",
    "Delete every third sentence, then bridge the gaps.",
    "End every sentence on a stressed syllable.",
    "Fold a sheet. Write a line, fold it away, pass it on. Unfold only at the end.",
    "Forbid the letter your own name begins with. Write a page.",
    "Give every character the vocabulary of a trade they do not practice.",
    "Give one object in the scene a history nobody mentions.",
    "Give the narration to whoever comes off worst.",
    "Halve the word count without losing an event.",
    "Impose a form that has nothing to do with the content.",
    "Insert a sentence from another book every ten lines. Make them belong.",
    "Let a coin settle every fork in the plot for one page.",
    "Let each section be shorter than the one before it.",
    "Narrate it from far enough away that the people are small.",
    "Number your paragraphs, then reorder them by dice.",
    "Open the nearest book anywhere. Take the first whole sentence as your opening.",
    "Pick a word you did not choose. Make it the hinge.",
    "Put the ending on page one and keep going.",
    "Remove every adverb, then every simile.",
    "Repeat one word in every sentence until it stops meaning anything.",
    "Replace all proper names with the name of a color.",
    "Replace each key word with its dictionary definition. Now do it again.",
    "Replace every adjective with its opposite and change nothing else.",
    "Replace every noun with the seventh noun that follows it in a dictionary.",
    "Replace every verb with a quieter one.",
    "Retell it as the version that gets told at funerals.",
    "Retell it in the voice of someone who was not there.",
    "Retell the scene as a complaint to a company.",
    "Retell the scene as a recipe.",
    "Retell the scene as a weather report.",
    "Retell the scene as an apology.",
    "Retell the scene as an instruction manual.",
    "Retell the scene as evidence given under oath.",
    "Rewrite the passage in the second person.",
    "Same event, three tellings\n\t-to a stranger\n\t-to a lawyer\n\t-to yourself",
    "Say the next page aloud and transcribe it exactly.",
    "Set a rule at the top of the page. Break it once, on purpose.",
    "Set a timer for four minutes. Stop mid-sentence and leave it there.",
    "Strip all punctuation. Put back only what the sense demands.",
    "Swap every abstract noun for something you could hold in one hand.",
    "Take a constraint from a form you dislike and use it honestly.",
    "Take three words from three different pages. Every paragraph must hold all three.",
    "Tell it backwards, last event first.",
    "Tell it entirely in the future tense.",
    "Tell one small event nine times, changing only the register.",
    "Use no word longer than four letters.",
    "Use only letters that sit on the line, with nothing looping above or below it.",
    "Work under two constraints that fight each other.",
    "Write a glossary for a place you invented.",
    "Write a hundred words. Cut to fifty. Cut to twenty-five. Cut to ten.",
    "Write a paragraph in which no word appears twice.",
    "Write a paragraph that rhymes but does not look like a poem.",
    "Write a paragraph whose sentences each shorten by one word.",
    "Write a passage that can be read from its last line to its first.",
    "Write a passage using only one vowel throughout.",
    "Write a poem whose every line is one word, each a letter longer than the last.",
    "Write a sentence that reads the same in both directions.",
    "Write for the ear only. Read it aloud and cut whatever stumbles.",
    "Write in the dark and read it in the morning.",
    "Write it as a list and see what survives.",
    "Write it out longhand once before touching a keyboard.",
    "Write it somewhere you will be interrupted.",
    "Write nothing today. Note tomorrow what you would have written.",
    "Write one page with your other hand.",
    "Write only dialogue, in which no one says what they mean.",
    "Write only in sentences of exactly seven words.",
    "Write only the questions and let the answers stay missing.",
    "Write only what happens between the scenes.",
    "Write standing, and stop when you want to sit.",
    "Write the footnotes to a text that does not exist.",
    "Write the index for a book you have not written.",
    "Write the last line first, then earn it.",
    "Write the next paragraph without using the letter E.",
    "Write the scene as the one who left remembers it ten years on.",
    "Write the scene at\n\t-a hundred words\n\t-ten words\n\t-one word",
    "Write the scene from the position of an object in the room.",
    "Write the scene twice: once as farce, once as elegy.",
    "Write the scene, then write it again from memory a day later.",
    "Write the whole thing as one sentence.",
    "Write to a fixed length: not one word over, not one under.",
    "Write without stopping for ten minutes. Do not steer and do not reread.",
];
