//! An examen: a review of the day just spent.
//!
//! The cards are written for this crate. Their register - second person, past
//! tense, and free of verdicts - is drawn from the traditions of daily
//! self-examination rather than from their texts: the Ignatian examen, the
//! Stoic evening review Seneca describes in `De Ira`, Marcus Aurelius on other
//! people's faults, Epictetus on what is and is not ours to move, and the
//! Proust questionnaire's habit of asking a preference in order to learn a
//! character. No card quotes any of them.
//!
//! Ask one at the end of a day. The deck does not tell you that you did well.

use crate::{Deck, Provenance};

/// The examen deck.
pub const DECK: Deck = Deck {
    id: "examen",
    name: "Examen",
    blurb: "Questions for the end of a day.",
    provenance: Provenance::Original,
    cards: CARDS,
};

const CARDS: &[&str] = &[
    "Account for today\n\t-what you spent\n\t-what you were given",
    "At what hour today were you most yourself?",
    "Forgive yourself for one hour of today. Choose which.",
    "How did you sleep, and what did you blame?",
    "How many hours of today can you account for?",
    "How much of today was quiet?",
    "How much of today will matter in a year?",
    "How often today did you reach for a screen with no reason?",
    "If today is the pattern, where does the pattern end?",
    "If today repeated, what would you keep?",
    "Name someone who thought about you today.",
    "Name today in one word. Now defend the word.",
    "Name today's\n\t-best hour\n\t-worst hour\n\t-hour you cannot recall",
    "Of everything that troubled you today, how much was yours to move?",
    "Say what today cost you.",
    "Set down one thing you have carried all week.",
    "Something moved you today and you moved past it. What was it?",
    "Today\n\t-what you chose\n\t-what chose you",
    "Tomorrow\n\t-one thing to begin\n\t-one thing to drop",
    "Walk back through the day. Where does your attention snag?",
    "Was the hard part of today the part you expected?",
    "Was today unusual? Say how, exactly.",
    "Were you alone today? Was it a choice?",
    "What angered you today? Was it worth the anger?",
    "What are you carrying into sleep that you can set down?",
    "What did today give you that you did not ask for?",
    "What did today teach you that tomorrow will test?",
    "What did you admire in someone today? Do you have it?",
    "What did you avoid today?",
    "What did you buy today? What was it standing in for?",
    "What did you consent to today without meaning to?",
    "What did you defend today? Is it yours to defend?",
    "What did you do today only because you were seen?",
    "What did you do today that no one asked for?",
    "What did you do today that you could not have done a year ago?",
    "What did you do today that you will do ten thousand more times?",
    "What did you do well today? Say it without hedging.",
    "What did you envy today? What does that tell you?",
    "What did you fear today that has not happened?",
    "What did you finish? What did you only touch?",
    "What did you get wrong today and not admit?",
    "What did you leave unsaid? Why?",
    "What did you look at longest today?",
    "What did you make today?",
    "What did you not finish reading, and why?",
    "What did you postpone again?",
    "What did you pretend not to know today?",
    "What did you read today that you will remember next week?",
    "What did you receive today and record as owed?",
    "What did you rehearse today that never happened?",
    "What did you say today only to fill a silence?",
    "What did you say today that you would not say to their face?",
    "What did you spend today trying to control?",
    "What did you tell yourself today that you half believe?",
    "What did you want today? Do you still want it?",
    "What did your body ask for today that you refused?",
    "What do you own that you did not think about today?",
    "What hurt today? Has it hurt before?",
    "What is the first thing you remember about today? Why that one?",
    "What is the most honest sentence you could write about today?",
    "What made you laugh today, and were you alone?",
    "What mood did you carry home? Where did you pick it up?",
    "What one thing done tomorrow would make today make sense?",
    "What took longer than it should have? Why?",
    "What went right today that you had no hand in?",
    "What will you meet tomorrow that you already dread? Name it plainly.",
    "What worked so well today that you failed to notice it?",
    "What would an unkind stranger say about today? Is any of it true?",
    "What would make tomorrow easier, and will you do it tonight?",
    "What would someone who loves you say about today?",
    "What would you have done today if no one would ever know?",
    "When did you last eat without doing something else?",
    "When did you last move without going anywhere?",
    "Where did today go?",
    "Where did you argue with something already settled?",
    "Where did you feel today in your body?",
    "Where did you perform today instead of act?",
    "Where did you spend someone else's patience?",
    "Where did you take the easier road? Was it the wrong road?",
    "Where did your attention go when you stopped steering it?",
    "Where were you unkind today? What did it buy you?",
    "Which emotion ran today? Did you choose it?",
    "Which hour of today would you hand back?",
    "Which hour of today would you live again?",
    "Who did you make smaller today?",
    "Who made your day easier without being thanked?",
    "Who needed something from you today that they could not ask for?",
    "Who was difficult today? What were they protecting?",
    "Whom did you help without deciding to?",
    "Whom did you not listen to?",
    "Whose approval were you working for today?",
    "Whose fault did you dwell on today? Is it also yours?",
];
